### ISSUE TITLE
Fatal Error v0.0.3 & 0.0.7

### ISSUE THREAD

**Issue by djok** [biancode/node-red-contrib-bacnet#1]
9 Dec 16:48:53 - [info] Node-RED version: v0.17.5
9 Dec 16:48:53 - [info] Node.js  version: v6.12.2
9 Dec 16:48:53 - [info] Linux 4.4.0-103-generic x64 LE

9 Dec 16:49:02 - TypeError: o.devices.add is not a function
    at EventEmitter.<anonymous> (/home/djok/.node-red/node_modules/node-red-contrib-bacnet/bacnet/bacnet-client.js:1:445)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at processUnconfirmedServiceRequest (/home/djok/.node-red/node_modules/bacstack/lib/bacnet-client.js:249:12)
    at handlePdu (/home/djok/.node-red/node_modules/bacstack/lib/bacnet-client.js:286:9)
    at handleNpdu (/home/djok/.node-red/node_modules/bacstack/lib/bacnet-client.js:343:5)
    at self.receiveData (/home/djok/.node-red/node_modules/bacstack/lib/bacnet-client.js:354:7)
    at Socket.<anonymous> (/home/djok/.node-red/node_modules/bacstack/lib/bacnet-transport.js:13:25)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:548:8)

**Comment by biancode** [comment]
Yes, had to be a push.

**Comment by biancode** [comment]
please, try v0.0.8 - I need to find a working Simulator to test more

**Comment by biancode** [comment]
see more with `DEBUG=bacnet* node-red -v`
